x-web-app: &web-app
  build:
    context: .
    dockerfile: Dockerfile.dev
  environment:
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_PORT: 5432
    DB_HOST: postgres
    RAILS_ENV: development
    EDITOR: 'vim'
    WEB_CONCURRENCY: 0
  stdin_open: true
  tty: true
  volumes:
    - .:/rails
    - node-modules:/rails/node_modules
    - bootsnap-cache:/rails/tmp/cache/bootsnap

services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    <<: *web-app
    entrypoint: ./bin/docker-dev-entrypoint
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000/tcp"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  node-modules:
  bootsnap-cache:
